proc expect_exact {text} {
	expect {
		-exact $text {}
		timeout {
			puts "Expected: '$text'"
			exit 1
		}
		eof {
			puts "Program ended too early (wanted '$text')"
			exit 1
		}
	}
}

proc spawn_binary {} {
	global env timeout spawn_id
	if {[info exists env(COVERAGE_OUT)]} {
		set timeout 30
		spawn valgrind --tool=callgrind --callgrind-out-file=$env(COVERAGE_OUT) --quiet ./build/coverage/main
	} else {
		spawn ./build/main
	}
}
